language: php

git:
  depth: 5

matrix:
  include:
    - php: 7.4
    - php: 7.3
      env: COVERAGE=on
      dist: trusty
    - php: 7.3
      env: STYLECHECK=on

install:
  - composer self-update
  - if [[ "$STYLECHECK" != "on" ]]; then composer require phpunit/phpunit:^7 phug/split --no-update; fi;
  - if [[ "$STYLECHECK" = "on" ]]; then composer require squizlabs/php_codesniffer --no-update; fi;
  - composer install
  - |
    if [[ "$STYLECHECK" != "on" ]]; then
      mkdir -p tests/Phug && \
      vendor/bin/split copy https://github.com/phug-php/phug.git tests/Phug/ --filters=tests/Phug/Invoker*;
    fi;

script:
  - if [[ "$STYLECHECK" != "on" && "$COVERAGE" != "on" ]]; then vendor/bin/phpunit; fi;
  - if [[ "$COVERAGE" = "on" ]]; then vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml; fi;
  - if [[ "$STYLECHECK" = "on" ]]; then vendor/bin/phpcs; fi;

notifications:
  slack: phug:nzXFnxhU14RWK2EQSDL0u08z

addons:
  code_climate:
    repo_token: 9c3a9306538669f298fd9c41ae93f5446a617c02fdfae9c7a72fc69dd015d010
